load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "util",
    srcs = ["util.go"],
    importpath = "golang.org/x/tools/internal/mcp/internal/util",
    visibility = ["//internal/mcp:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":util",
    visibility = ["//internal/mcp:__subpackages__"],
)

go_test(
    name = "util_test",
    srcs = ["util_test.go"],
    embed = [":util"],
)
