load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "quic",
    srcs = [
        "ack_delay.go",
        "acks.go",
        "atomic_bits.go",
        "config.go",
        "congestion_reno.go",
        "conn.go",
        "conn_close.go",
        "conn_flow.go",
        "conn_id.go",
        "conn_loss.go",
        "conn_recv.go",
        "conn_send.go",
        "conn_streams.go",
        "crypto_stream.go",
        "dgram.go",
        "doc.go",
        "endpoint.go",
        "errors.go",
        "frame_debug.go",
        "gate.go",
        "idle.go",
        "log.go",
        "loss.go",
        "math.go",
        "pacer.go",
        "packet.go",
        "packet_number.go",
        "packet_parser.go",
        "packet_protection.go",
        "packet_writer.go",
        "path.go",
        "ping.go",
        "pipe.go",
        "qlog.go",
        "queue.go",
        "quic.go",
        "rangeset.go",
        "retry.go",
        "rtt.go",
        "sent_packet.go",
        "sent_packet_list.go",
        "sent_val.go",
        "skip.go",
        "stateless_reset.go",
        "stream.go",
        "stream_limits.go",
        "tls.go",
        "transport_params.go",
        "udp.go",
        "udp_darwin.go",
        "udp_linux.go",
        "udp_msg.go",
        "udp_other.go",
        "udp_packetconn.go",
    ],
    importpath = "golang.org/x/net/quic",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/quic/quicwire",
        "@org_golang_x_crypto//chacha20",
        "@org_golang_x_crypto//chacha20poly1305",
        "@org_golang_x_crypto//cryptobyte",
        "@org_golang_x_crypto//hkdf",
    ] + select({
        "@io_bazel_rules_go//go/platform:android": [
            "@org_golang_x_sys//unix",
        ],
        "@io_bazel_rules_go//go/platform:darwin": [
            "@org_golang_x_sys//unix",
        ],
        "@io_bazel_rules_go//go/platform:ios": [
            "@org_golang_x_sys//unix",
        ],
        "@io_bazel_rules_go//go/platform:linux": [
            "@org_golang_x_sys//unix",
        ],
        "//conditions:default": [],
    }),
)

alias(
    name = "go_default_library",
    actual = ":quic",
    visibility = ["//visibility:public"],
)

go_test(
    name = "quic_test",
    srcs = [
        "ack_delay_test.go",
        "acks_test.go",
        "bench_test.go",
        "config_test.go",
        "congestion_reno_test.go",
        "conn_async_test.go",
        "conn_close_test.go",
        "conn_flow_test.go",
        "conn_id_test.go",
        "conn_loss_test.go",
        "conn_recv_test.go",
        "conn_send_test.go",
        "conn_streams_test.go",
        "conn_test.go",
        "crypto_stream_test.go",
        "endpoint_test.go",
        "gate_test.go",
        "gotraceback_test.go",
        "idle_test.go",
        "key_update_test.go",
        "loss_test.go",
        "main_test.go",
        "pacer_test.go",
        "packet_codec_test.go",
        "packet_number_test.go",
        "packet_protection_test.go",
        "packet_test.go",
        "path_test.go",
        "ping_test.go",
        "pipe_test.go",
        "qlog_test.go",
        "queue_test.go",
        "quic_test.go",
        "rangeset_test.go",
        "retry_test.go",
        "rtt_test.go",
        "sent_packet_list_test.go",
        "sent_packet_test.go",
        "sent_val_test.go",
        "skip_test.go",
        "stateless_reset_test.go",
        "stream_limits_test.go",
        "stream_test.go",
        "tls_test.go",
        "tlsconfig_test.go",
        "transport_params_test.go",
        "udp_test.go",
        "version_test.go",
    ],
    embed = [":quic"],
    deps = [
        "//internal/quic/quicwire",
        "//internal/testcert",
        "//quic/qlog",
    ],
)
