load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "httpmux",
    srcs = ["httpmux.go"],
    importpath = "golang.org/x/tools/go/analysis/passes/httpmux",
    visibility = ["//visibility:public"],
    deps = [
        "//go/analysis",
        "//go/analysis/passes/inspect",
        "//go/ast/inspector",
        "//go/types/typeutil",
        "//internal/analysisinternal",
        "//internal/typesinternal",
        "@org_golang_x_mod//semver",
    ],
)

alias(
    name = "go_default_library",
    actual = ":httpmux",
    visibility = ["//visibility:public"],
)

go_test(
    name = "httpmux_test",
    srcs = ["httpmux_test.go"],
    embed = [":httpmux"],
    deps = ["//go/analysis/analysistest"],
)
