load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "expect",
    srcs = [
        "expect.go",
        "extract.go",
    ],
    importpath = "golang.org/x/tools/internal/expect",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
    deps = ["@org_golang_x_mod//modfile"],
)

alias(
    name = "go_default_library",
    actual = ":expect",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
)

go_test(
    name = "expect_test",
    srcs = ["expect_test.go"],
    deps = [":expect"],
)
