load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "internal",
    srcs = ["d.go"],
    importpath = "golang.org/x/tools/internal/gofix/testdata/src/a/internal",
    visibility = ["//internal/gofix/testdata/src/a:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":internal",
    visibility = ["//internal/gofix/testdata/src/a:__subpackages__"],
)
