module(
    name = "bazel_module_builder",
    version = "0.0.0",
)

bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "rules_go", version = "0.63.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.23.4")

bazel_dep(
    name = "gcc_toolchain",
    version = "0.12.0",
    dev_dependency = True,
)

gcc_toolchains = use_extension(
    "@gcc_toolchain//toolchain:module_extensions.bzl",
    "gcc_toolchains",
    dev_dependency = True,
)
gcc_toolchains.toolchain(
    name = "gcc_toolchain_x86_64",
    extra_cxxflags = [
        "-fdiagnostics-color=never",
        "-nostdinc",
        "-nostdinc++",
        "-B%workspace%/bin",
        # Force C++14 as default
        "-std=c++14",
    ],
    extra_ldflags = [
        "-lstdc++",
    ],
    target_arch = "x86_64",
)
use_repo(gcc_toolchains, "gcc_toolchain_x86_64")

register_toolchains(
    "@gcc_toolchain_x86_64//:cc_toolchain",
    # Register toolchains as dev dependencies so that we don't pollute the toolchain resolution of consumers.
    dev_dependency = True,
)
