load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "importsunsafe",
    srcs = ["i.go"],
    importpath = "golang.org/x/tools/go/analysis/passes/unusedwrite/testdata/src/importsunsafe",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":importsunsafe",
    visibility = ["//visibility:public"],
)
