load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "http2",
    srcs = [
        "ascii.go",
        "ciphers.go",
        "client_conn_pool.go",
        "config.go",
        "config_go124.go",
        "config_pre_go124.go",
        "databuffer.go",
        "errors.go",
        "flow.go",
        "frame.go",
        "gotrack.go",
        "http2.go",
        "pipe.go",
        "server.go",
        "timer.go",
        "transport.go",
        "unencrypted.go",
        "write.go",
        "writesched.go",
        "writesched_priority.go",
        "writesched_random.go",
        "writesched_roundrobin.go",
    ],
    importpath = "golang.org/x/net/http2",
    visibility = ["//visibility:public"],
    deps = [
        "//http/httpguts",
        "//http2/hpack",
        "//idna",
        "//internal/httpcommon",
    ],
)

alias(
    name = "go_default_library",
    actual = ":http2",
    visibility = ["//visibility:public"],
)

go_test(
    name = "http2_test",
    srcs = [
        "ascii_test.go",
        "ciphers_test.go",
        "clientconn_test.go",
        "config_test.go",
        "connframes_test.go",
        "databuffer_test.go",
        "errors_test.go",
        "flow_test.go",
        "frame_test.go",
        "gotrack_test.go",
        "http2_test.go",
        "netconn_test.go",
        "pipe_test.go",
        "server_push_test.go",
        "server_test.go",
        "sync_test.go",
        "transport_test.go",
        "writesched_priority_test.go",
        "writesched_random_test.go",
        "writesched_roundrobin_test.go",
        "writesched_test.go",
    ],
    embed = [":http2"],
    deps = [
        "//http2/hpack",
        "//internal/gate",
    ],
)
