
load("@package_metadata//rules:package_metadata.bzl", "package_metadata")
load("@rules_license//rules:package_info.bzl", "package_info")

package_metadata(
    name = "package_metadata",
    purl = "pkg:golang/github.com/pmezard/go-difflib@v1.0.0",
    visibility = [
        "//:__subpackages__",
    ],
)

package_info(
    name = "gazelle_generated_package_info",
    package_name = "github.com/pmezard/go-difflib",
    package_url = "https://github.com/pmezard/go-difflib",
    package_version = "1.0.0",
    purl = "pkg:golang/github.com/pmezard/go-difflib@v1.0.0",
    visibility = ["//:__subpackages__"],
)
