load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tokeninternal",
    srcs = [
        "tokeninternal.go",
        "tokeninternal_go124.go",
        "tokeninternal_go125.go",
    ],
    importpath = "golang.org/x/tools/internal/tokeninternal",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
)

alias(
    name = "go_default_library",
    actual = ":tokeninternal",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
)

go_test(
    name = "tokeninternal_test",
    srcs = ["tokeninternal_test.go"],
    deps = [":tokeninternal"],
)
