load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_binary")

gazelle(name = "gazelle")

go_binary(
    name = "hello",
    srcs = [":main.go"],
    importpath = "github.com/puqu-io/nixcon2026-the-ministry-of-silly-builds-bazel-9-derivation-builder/examples/go_external",
    deps = [
        "@com_github_google_uuid//:uuid",
    ],
    visibility = ["//visibility:public"],
)
