load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gocommand",
    srcs = [
        "invoke.go",
        "invoke_notunix.go",
        "invoke_unix.go",
        "vendor.go",
        "version.go",
    ],
    importpath = "golang.org/x/tools/internal/gocommand",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
    deps = [
        "//internal/event",
        "//internal/event/keys",
        "//internal/event/label",
        "@org_golang_x_mod//semver",
    ],
)

alias(
    name = "go_default_library",
    actual = ":gocommand",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
)

go_test(
    name = "gocommand_test",
    srcs = [
        "invoke_test.go",
        "version_test.go",
    ],
    embed = [":gocommand"],
    deps = [
        "//internal/testenv",
        "@org_golang_x_sync//errgroup",
    ],
)
