load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gate",
    srcs = ["gate.go"],
    importpath = "golang.org/x/net/internal/gate",
    visibility = ["//:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":gate",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "gate_test",
    srcs = ["gate_test.go"],
    deps = [":gate"],
)
