load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "importgraph",
    srcs = ["graph.go"],
    importpath = "golang.org/x/tools/refactor/importgraph",
    visibility = ["//visibility:public"],
    deps = ["//go/buildutil"],
)

alias(
    name = "go_default_library",
    actual = ":importgraph",
    visibility = ["//visibility:public"],
)

go_test(
    name = "importgraph_test",
    srcs = ["graph_test.go"],
    deps = select({
        "@io_bazel_rules_go//go/platform:aix": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:darwin": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:dragonfly": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:freebsd": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:illumos": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:ios": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:js": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:linux": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:netbsd": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:openbsd": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:osx": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:plan9": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:qnx": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:solaris": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "@io_bazel_rules_go//go/platform:windows": [
            ":importgraph",
            "//internal/packagestest",
        ],
        "//conditions:default": [],
    }),
)
