load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "proxydir",
    srcs = ["proxydir.go"],
    importpath = "golang.org/x/tools/internal/proxydir",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
)

alias(
    name = "go_default_library",
    actual = ":proxydir",
    visibility = [
        "//:__subpackages__",
        "@org_golang_x_tools_go_vcs//:__subpackages__",
    ],
)

go_test(
    name = "proxydir_test",
    srcs = ["proxydir_test.go"],
    embed = [":proxydir"],
)
